### ISSUE TITLE
work with librejs 

### ISSUE THREAD

**Issue by fkooman** [raucao/sharesome#42]
I'm using IceCat with LibreJS (https://addons.mozilla.org/en-US/firefox/addon/librejs/) and Sharesome doesn't work because the license of the files is not made clear to LibreJS:

```
  <!--LibreJS: script blocked.--><script data-librejs-blocked-src="assets/e06bb2a9.vendor.min.js" data-librejs-reason="error parsing: 1139be7836eb290fe0ed313c949501f823ba7c31" data-librejs="rejected" type="librejs/blocked"></script>

  <!--LibreJS: script blocked.--><script data-librejs-blocked-src="assets/83df10b7.app.min.js" data-librejs-reason="This script is detected as nonfree, external, and as defining functions or methods" data-librejs="rejected" type="librejs/blocked"></script>
```

(and a few more are blocked). As they are all free software, it should be possible to get this sorted out, but probably also depend on the deploy scripts for 5apps.

Instructions on how to do this are available here: http://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by skddc** [comment]
My apps on 5apps contain a license header on top of the HTML: view-source:https://sharesome.5apps.com

So it would be enough to add `@licstart` and `@licend` around that?

**Comment by fkooman** [comment]
It may be a little bit more involved than that. It may also be necessary to list the license of all the dependencies of the dependencies as well... See also http://www.gnu.org/licenses/javascript-labels.html for minified JS.

**Comment by skddc** [comment]
I'm not really willing to put one of those label tables in my code. It's the worst solution to this problem I can think of, and completely unmaintainable when using a gazillion node modules as nested dependencies (which this app does). The table alone would be 10 times the size of my source HTML.

So unless there's a proper standard for declaring it, I can't accommodate this blocker I'm afraid.
